#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01).
# www --> 103083-lb-01 3.86.7.224
# web-01 --> 103083-web-01 18.206.208.237
# web-02 --> 103083-web-02 54.157.153.196

dns_config () {
    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  dns_config "$1" "www"
  dns_config "$1" "lb-01"
  dns_config "$1" "web-01"
  dns_config "$1" "web-02"
elif [ "$#" == 2 ]
then
  dns_config "$1" "$2"
fi
