#!/usr/bin/env bash
# Installs, configures, and starts the server

apt-get update
apt-get install -y nginx

mkdir /var/www/html
touch /var/www/html/index.html
echo "Hello Word!" > /var/www/html/index.html

new_config=\
"server {
	listen 80;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location /redirect_me {
		return 301 https://www.freecodecamp.org permanent;
	}

	error_page 404 /404.html;
        location  /404.html {
		root /etc/nginx/html;
	        internal;
        }
}"

echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "$new_config" > /etc/nginx/sites-available/default

service nginx restart
