#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y install haproxy

# Configuring files

server_config = \
"
frontend gkwoode.tech-frontend
        bind *:80
        mode http
        default_backend gkwoode.tech-backend
backend gkwoode.tech-backend
        balance roundrobin
        server 103083-web-01 18.206.208.237:80 check
        server 103083-web-02 54.157.153.196:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
